### ISSUE TITLE
Commands to start tasks without using QV  management console

### ISSUE THREAD

**Issue by jk1510karti** [RobWunderlich/Qlikview-Components#53]
Hi,

Could you please list set of commands for starting list of tasks in QvMC. I am looking for some automated way of starting tasks without using Qv Management console. 

Or can anyone suggest what could be the best way to achieve this using powershell scripts ?

**Comment by RobWunderlich** [comment]
What you want to use is the EDX facility, which is not part of QVC. It's part of the QlikView product. Doc here, including an exe you can download to start tasks from the command line. 
https://community.qlik.com/docs/DOC-2650

**Comment by jk1510karti** [comment]
@RobWunderlich  - 

The below example shows reloading of QV data, i.e reloading of task “example.qvw”. 

I just wanted to know, whether Reloading of task from command line & Starting a task from QV console(Right click on task -> Start) are same ?

Example:
“C:\Program Files\QlikView\qv.exe" "C:\qlikview_docs\example.qvw" /R” 


if not, Please let me know what is the EDX commands for following actions

-	Start the tasks in QV from command line
-	Stop the tasks in QV from command line
-	Check the running status of QV tasks from command line
-	Schedule tasks in QV from command line

Its quite urgent.! Your help is much appreciated.

**Comment by veglar** [comment]
I don't believe you can do command triggers straight out of the box in QlikView. You will need an application that transforms your commands to QlikView API. Check out [Trigger QV  Task using command line arguments](https://community.qlik.com/docs/DOC-7706)  for an how to on the project Rob mentioned earlier. The [qv-edx-trigger](https://github.com/braathen/qv-edx-trigger) is a github protect you also could look into.

**Comment by RobWunderlich** [comment]
Hello,
This question is not related to this QVC project. A better place to ask
this question is the Qlik community https://community.qlik.com/welcome

On Oct 18, 2016, at 1:08 AM, jk1510karti <notifications@github.com> wrote:

@RobWunderlich <https://github.com/RobWunderlich> -

The below example shows reloading of QV data, i.e reloading of task
“example.qvw”.

I just wanted to know, whether Reloading of task from command line &
Starting a task from QV console(Right click on task -> Start) are same ?

Example:
“C:\Program Files\QlikView\qv.exe" "C:\qlikview_docs\example.qvw" /R”

if not, Please let me know what is the EDX commands for following actions

   - Start the tasks in QV from command line
   - Stop the tasks in QV from command line
   - Check the running status of QV tasks from command line
   - Schedule tasks in QV from command line

Its quite urgent.! Your help is much appreciated.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/RobWunderlich/Qlikview-Components/issues/53#issuecomment-254407953>,
or mute the thread
