### ISSUE TITLE
Flexible YTD

### ISSUE THREAD

**Issue by Aviaf47** [RobWunderlich/Qlikview-Components#64]
IS there a way to use YTD so that if a date selection is made, the YTD can shift to the max YTD in that selection?

For example, sales for the current month haven't come in yet, so when comparing YTD Actuals to Budget actuals, I would want to select the months other than the current month to show a proper comparable.

**Comment by RobWunderlich** [comment]
You should be able to select a prior month from a list box and have YTD
honer that. Is it not working that way or are you trying to do something
else?

On Jun 12, 2017, at 12:26 PM, Aviaf47 <notifications@github.com> wrote:

IS there a way to use YTD so that if a date selection is made, the YTD can
shift to the max YTD in that selection?

For example, sales for the current month haven't come in yet, so when
comparing YTD Actuals to Budget actuals, I would want to select the months
other than the current month to show a proper comparable.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/RobWunderlich/Qlikview-Components/issues/64>, or mute
the thread

**Comment by Aviaf47** [comment]
Had an error in my code. All good.
