### ISSUE TITLE
YTD past current date

### ISSUE THREAD

**Issue by Aviaf47** [RobWunderlich/Qlikview-Components#65]
YTD automatically pulls in the YTD from a future year in my files when I have budget for future years for some reason...

**Comment by RobWunderlich** [comment]
I understand. I have a fix in the works for that. The rule I'm implementing
is that YTD will never be later than the reload date. Will that work for
you?

On Jun 12, 2017, at 1:29 PM, Aviaf47 <notifications@github.com> wrote:

YTD automatically pulls in the YTD from a future year in my files when I
have budget for future years for some reason...

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/RobWunderlich/Qlikview-Components/issues/65>, or mute
the thread

**Comment by Aviaf47** [comment]
Yes, that would be great.

**Comment by RobWunderlich** [comment]
Fixed in 11.2
