### ISSUE TITLE
Calendar, Qvc.Calendar.v.SparseDates

### ISSUE THREAD

**Issue by GorumDerVan** [RobWunderlich/Qlikview-Components#89]
Hi Rob,
On which line must the Qvc.Calendar.v.SparseDates variable be set in QVC.qvs to work?

Thanks

**Comment by RobWunderlich** [comment]
Hi,
At any point after the include of qvc.qvs and before rage Call to
QVC.Calender.

On Oct 1, 2019, at 11:45 PM, GorumDerVan <notifications@github.com> wrote:

Hi Rob,
On which line must the Qvc.Calendar.v.SparseDates variable be set in
QVC.qvs to work?

Thanks

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/RobWunderlich/Qlikview-Components/issues/89?email_source=notifications&email_token=ABOOPBHRHUKAX4FG3GVEGTLQMQ7QPA5CNFSM4I4SO4F2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HPBLN6Q>,
or mute the thread
