### ISSUE TITLE
Issues with LinkTable

### ISSUE THREAD

**Issue by bmenicucci** [RobWunderlich/Qlikview-Components#93]
Hello Rob,
I need your help as I don't understand why the heck these two tables are not linking correctly. I have a facts table which I'd like to link to Calendar using QVC.LinkTable routine, but it looks there's something preventing it to happens.😵
Enclosed you'll find a sample application. Any suggestion or hint will be highly appreciated!
[Test_kpi.qvw.zip](https://github.com/RobWunderlich/Qlikview-Components/files/4493150/Test_kpi.qvw.zip)

Thanks, Brunello

**Comment by RobWunderlich** [comment]
The Qvc.LinkTable routine, as coded, requires that each call use the same
fields. You are generating two different key values because you are using
two different field lists.

*CALL* *Qvc.LinkTable*('LinkTable','Calendar','KeyCalendar');
*CALL* *Qvc.LinkTable*
('LinkTable','KPILavorazioni','KeyKPILav,KeyCalendar');

I'm not clear on why you need a link table to link to the calendar?

Kind Regards,
Rob Wunderlich

http://MastersSummit.com   @QlikMasters
http://QlikviewCookbook.com   @QVCookbook
http://www.easyqlik.com  QViewer

**Comment by bmenicucci** [comment]
Ok, in that case I was completely misusing the subroutine: my understanding
was that I could generate a LinkTable for all the Keys I needed. Thus, in
the sample I have a lot of tables but these two particular ones weren't
correctly linked... now I see why
Sorry, my fault 🙏
